-- Do not edit this file, it's generated from the yaml file

DROP TABLE IF EXISTS public.devices CASCADE;
CREATE TABLE public.devices (
	version float,
	vendor character varying,
	model character varying,
	build character varying,
	blobs jsonb,
	available bool,
	builds bool,
	UNIQUE(build)
);
DROP TABLE IF EXISTS public.specs CASCADE;
CREATE TABLE public.specs (
	release timestamp without time zone,
	arch public.archtypes,
	soc character varying,
	cpus character varying[],
	peripherals character varying[],
	ram int,
	bluetooth character varying,
	wifi public.wifitypes[],
	build character varying,
	gpu character varying,
	network public.nettypes[],
	kernel float
);

DROP TABLE IF EXISTS public.gsmarena CASCADE;
CREATE TABLE public.gsmarena (
	vendor character varying,
	model character varying,
	annnounced character varying,
	chipset character varying,
	cpu character varying,
	sensors character varying,
	wlan character varying,
	status public.devstatus
);


